name: GitHub Pages
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'README.md'
      - 'Trivy.md'
      - '.github/workflows/gh-pages.yml'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
         mdbook-version: '0.4.5'
      - name: Build mdBook
        working-directory: ./docs
        run: mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          publish_dir: ./docs/book
          publish_branch: gh-pages
